stages:
  - choose-environment
  - deploy

variables:
  IMAGE_REPOSITORY: 192.168.49.2:30002/orange/my-spring-boot-app
  IMAGE_TAG: "latest"

choose-environment:
  stage: choose-environment
  script:
    - echo "Please select the environment for deployment:"
    - echo "1. Dev"
    - echo "2. Test"
  when: manual
  allow_failure: false

# Create separate jobs for Dev and Test, which will run based on the chosen environment.
deploy:
  stage: deploy
  script:
    - echo "Deploying to the selected environment..."
    - |
      if [[ "$ENVIRONMENT" == "Dev" ]]; then
        NAMESPACE="dev"
      elif [[ "$ENVIRONMENT" == "Test" ]]; then
        NAMESPACE="test"
      else
        echo "Invalid environment selection."
        exit 1
      fi
    - helm upgrade --install spring-boot-app ./spring-boot-app --namespace $NAMESPACE --set image.repository=$IMAGE_REPOSITORY --set image.tag=$IMAGE_TAG
  only:
    - master
  environment:
    name: $ENVIRONMENT
  when: on_success

before_script:

  - docker login -u "$NEXUS_USERNAME" -p "$NEXUS_PASSWORD" http://192.168.49.2:30002
  

variables:
  ENVIRONMENT:
    description: "Choose the environment for deployment: Dev or Test"
    value: "Dev"  # Default value
    options:
      - Dev
      - Test

